CREATE TABLE qar_sample (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    sample_at timestamptz NOT NULL,
    source_time_text varchar(16) NOT NULL,
    flight_no varchar(20) NOT NULL,
    origin varchar(4) NOT NULL,
    destination varchar(4) NOT NULL,
    air_ground_status varchar(16) NOT NULL,
    altitude_ft numeric(10,2),
    computed_air_speed_kt numeric(10,3),
    ground_speed_kt numeric(10,3),
    latitude double precision,
    longitude double precision,
    track_angle_deg numeric(7,3),
    heading_deg numeric(7,3),
    pitch_deg numeric(7,3),
    roll_deg numeric(7,3),
    left_fuel_qty numeric(14,3),
    right_fuel_qty numeric(14,3),
    center_fuel_qty numeric(14,3),
    low_fuel_warning boolean,
    distance_to_go_nm numeric(12,3),
    destination_eta_text varchar(32),
    frame_count bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_qar_sample_record UNIQUE (record_id),
    CONSTRAINT ck_qar_source_time CHECK (source_time_text ~ '^[0-9]{2}:[0-9]{2}:[0-9]{2}$'),
    CONSTRAINT ck_qar_origin CHECK (origin ~ '^[A-Z0-9]{4}$'),
    CONSTRAINT ck_qar_destination CHECK (destination ~ '^[A-Z0-9]{4}$'),
    CONSTRAINT ck_qar_air_speed CHECK (computed_air_speed_kt IS NULL OR computed_air_speed_kt >= 0),
    CONSTRAINT ck_qar_ground_speed CHECK (ground_speed_kt IS NULL OR ground_speed_kt >= 0),
    CONSTRAINT ck_qar_latitude CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_qar_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_qar_track CHECK (track_angle_deg IS NULL OR track_angle_deg BETWEEN 0 AND 360),
    CONSTRAINT ck_qar_heading CHECK (heading_deg IS NULL OR heading_deg BETWEEN 0 AND 360),
    CONSTRAINT ck_qar_left_fuel CHECK (left_fuel_qty IS NULL OR left_fuel_qty >= 0),
    CONSTRAINT ck_qar_right_fuel CHECK (right_fuel_qty IS NULL OR right_fuel_qty >= 0),
    CONSTRAINT ck_qar_center_fuel CHECK (center_fuel_qty IS NULL OR center_fuel_qty >= 0),
    CONSTRAINT ck_qar_distance CHECK (distance_to_go_nm IS NULL OR distance_to_go_nm >= 0),
    CONSTRAINT ck_qar_frame_count CHECK (frame_count >= 0)
);

CREATE INDEX idx_qar_flight_sample ON qar_sample (flight_no, sample_at);
CREATE INDEX idx_qar_frame_count ON qar_sample (frame_count);
CREATE INDEX brin_qar_sample_at ON qar_sample USING brin (sample_at);

CREATE TABLE simulation_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    task_id varchar(64) NOT NULL,
    flight_no varchar(20) NOT NULL,
    scenario_name varchar(255) NOT NULL,
    status varchar(32) NOT NULL,
    phase varchar(32),
    terminal_count integer NOT NULL,
    started_at timestamptz NOT NULL,
    ended_at timestamptz,
    downlink_target_mbps numeric(12,3),
    statistics_window_seconds integer NOT NULL,
    total_bytes bigint NOT NULL,
    failure_reason varchar(2000),
    rerun_source_task_id varchar(64),
    archived boolean NOT NULL DEFAULT false,
    snapshot_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_simulation_task_record UNIQUE (record_id),
    CONSTRAINT ck_task_terminal_count CHECK (terminal_count >= 0),
    CONSTRAINT ck_task_ended_at CHECK (ended_at IS NULL OR ended_at >= started_at),
    CONSTRAINT ck_task_target_mbps CHECK (downlink_target_mbps IS NULL OR downlink_target_mbps >= 0),
    CONSTRAINT ck_task_window_seconds CHECK (statistics_window_seconds > 0),
    CONSTRAINT ck_task_total_bytes CHECK (total_bytes >= 0)
);

CREATE INDEX idx_task_id_snapshot ON simulation_task (task_id, snapshot_at DESC);
CREATE INDEX idx_task_flight_snapshot ON simulation_task (flight_no, snapshot_at DESC);
CREATE INDEX idx_task_status_snapshot ON simulation_task (status, snapshot_at DESC);

CREATE TABLE traffic_record (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    item_no integer NOT NULL,
    task_id varchar(64) NOT NULL,
    window_start timestamptz NOT NULL,
    window_end timestamptz NOT NULL,
    terminal_id varchar(32) NOT NULL,
    display_terminal_id varchar(32),
    seat_label varchar(16),
    application varchar(128) NOT NULL,
    protocol varchar(16) NOT NULL,
    direction varchar(16) NOT NULL,
    bytes_count bigint NOT NULL,
    packet_count bigint NOT NULL,
    throughput_mbps numeric(12,3) NOT NULL,
    peak_mbps numeric(12,3) NOT NULL,
    record_status varchar(32) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_traffic_record_item UNIQUE (record_id, item_no),
    CONSTRAINT ck_traffic_item_no CHECK (item_no >= 1),
    CONSTRAINT ck_traffic_window CHECK (window_end >= window_start),
    CONSTRAINT ck_traffic_bytes CHECK (bytes_count >= 0),
    CONSTRAINT ck_traffic_packets CHECK (packet_count >= 0),
    CONSTRAINT ck_traffic_throughput CHECK (throughput_mbps >= 0),
    CONSTRAINT ck_traffic_peak CHECK (peak_mbps >= 0)
);

CREATE INDEX idx_traffic_task_window ON traffic_record (task_id, window_start DESC);
CREATE INDEX idx_traffic_terminal_window ON traffic_record (terminal_id, window_start DESC);
CREATE INDEX idx_traffic_application_window ON traffic_record (application, window_start DESC);
CREATE INDEX brin_traffic_window_start ON traffic_record USING brin (window_start);

CREATE TABLE session_summary (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    item_no integer NOT NULL,
    session_id varchar(64) NOT NULL,
    task_id varchar(64) NOT NULL,
    terminal_id varchar(32) NOT NULL,
    display_terminal_id varchar(32),
    seat_label varchar(16),
    application varchar(128) NOT NULL,
    protocol varchar(16) NOT NULL,
    started_at timestamptz NOT NULL,
    duration_seconds bigint NOT NULL,
    uplink_bytes bigint NOT NULL,
    downlink_bytes bigint NOT NULL,
    average_throughput_mbps numeric(12,3) NOT NULL,
    peak_throughput_mbps numeric(12,3) NOT NULL,
    status varchar(32) NOT NULL,
    snapshot_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_session_summary_item UNIQUE (record_id, item_no),
    CONSTRAINT ck_session_item_no CHECK (item_no >= 1),
    CONSTRAINT ck_session_duration CHECK (duration_seconds >= 0),
    CONSTRAINT ck_session_uplink CHECK (uplink_bytes >= 0),
    CONSTRAINT ck_session_downlink CHECK (downlink_bytes >= 0),
    CONSTRAINT ck_session_avg_throughput CHECK (average_throughput_mbps >= 0),
    CONSTRAINT ck_session_peak_throughput CHECK (peak_throughput_mbps >= 0)
);

CREATE INDEX idx_session_task_session_snapshot
    ON session_summary (task_id, session_id, snapshot_at DESC);
CREATE INDEX idx_session_terminal_snapshot
    ON session_summary (terminal_id, snapshot_at DESC);
CREATE INDEX idx_session_status_snapshot
    ON session_summary (status, snapshot_at DESC);

CREATE TABLE smart_window_status (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    item_no integer NOT NULL,
    window_id integer NOT NULL,
    zone_id smallint NOT NULL,
    brightness_level smallint NOT NULL,
    connect_status boolean NOT NULL,
    status varchar(16) NOT NULL,
    event_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_window_status_item UNIQUE (record_id, item_no),
    CONSTRAINT uk_window_status_window UNIQUE (record_id, window_id),
    CONSTRAINT ck_window_item_no CHECK (item_no >= 1),
    CONSTRAINT ck_window_id CHECK (window_id BETWEEN 1 AND 200),
    CONSTRAINT ck_window_zone CHECK (zone_id BETWEEN 1 AND 3),
    CONSTRAINT ck_window_brightness CHECK (brightness_level BETWEEN 0 AND 10),
    CONSTRAINT ck_window_status CHECK (status IN ('NORMAL', 'FAULT', 'TEST'))
);

CREATE INDEX idx_window_id_event ON smart_window_status (window_id, event_at DESC);
CREATE INDEX idx_window_zone_event ON smart_window_status (zone_id, event_at DESC);
CREATE INDEX idx_window_status_event ON smart_window_status (status, event_at DESC);
CREATE INDEX idx_window_connect_event ON smart_window_status (connect_status, event_at DESC);

CREATE TABLE ife_633_behavior (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    item_no integer NOT NULL,
    event_at timestamptz NOT NULL,
    flight_no varchar(20) NOT NULL,
    pnr varchar(16) NOT NULL,
    seat_no varchar(8) NOT NULL,
    cabin_class varchar(16) NOT NULL,
    device_id varchar(32) NOT NULL,
    passenger_id varchar(32) NOT NULL,
    behavior_type varchar(32) NOT NULL,
    behavior_detail jsonb NOT NULL,
    error_code varchar(8),
    error_description varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_ife_633_item UNIQUE (record_id, item_no),
    CONSTRAINT ck_ife_633_item_no CHECK (item_no >= 1),
    CONSTRAINT ck_ife_633_cabin CHECK (cabin_class IN ('FIRST', 'BUSINESS', 'ECONOMY')),
    CONSTRAINT ck_ife_633_behavior CHECK (
        behavior_type IN ('MOVIE_PLAY', 'MUSIC_PLAY', 'CAST_SCREEN', 'WAP_BROWSING')
    ),
    CONSTRAINT ck_ife_633_detail_object CHECK (jsonb_typeof(behavior_detail) = 'object')
);

CREATE INDEX idx_ife_633_flight_event ON ife_633_behavior (flight_no, event_at DESC);
CREATE INDEX idx_ife_633_passenger_event ON ife_633_behavior (passenger_id, event_at DESC);
CREATE INDEX idx_ife_633_seat_event ON ife_633_behavior (seat_no, event_at DESC);
CREATE INDEX idx_ife_633_type_event ON ife_633_behavior (behavior_type, event_at DESC);

CREATE TABLE ife_cockrell_behavior (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    item_no integer NOT NULL,
    event_at timestamptz NOT NULL,
    flight_no varchar(20) NOT NULL,
    pnr varchar(16) NOT NULL,
    seat_no varchar(8) NOT NULL,
    cabin_class varchar(16) NOT NULL,
    device_id varchar(32) NOT NULL,
    passenger_id varchar(32) NOT NULL,
    behavior_type varchar(32) NOT NULL,
    behavior_detail jsonb NOT NULL,
    cover_mime_type varchar(32),
    cover_checksum varchar(64),
    error_code varchar(8),
    error_description varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uk_ife_cockrell_item UNIQUE (record_id, item_no),
    CONSTRAINT ck_ife_cockrell_item_no CHECK (item_no >= 1),
    CONSTRAINT ck_ife_cockrell_cabin CHECK (cabin_class IN ('FIRST', 'BUSINESS', 'ECONOMY')),
    CONSTRAINT ck_ife_cockrell_behavior CHECK (
        behavior_type IN ('MOVIE_PLAY', 'MUSIC_PLAY', 'WAP_BROWSING', 'SHOPPING')
    ),
    CONSTRAINT ck_ife_cockrell_detail_object CHECK (jsonb_typeof(behavior_detail) = 'object'),
    CONSTRAINT ck_ife_cockrell_checksum CHECK (
        cover_checksum IS NULL OR cover_checksum ~ '^[0-9a-fA-F]{64}$'
    )
);

CREATE INDEX idx_ife_cockrell_flight_event
    ON ife_cockrell_behavior (flight_no, event_at DESC);
CREATE INDEX idx_ife_cockrell_passenger_event
    ON ife_cockrell_behavior (passenger_id, event_at DESC);
CREATE INDEX idx_ife_cockrell_seat_event
    ON ife_cockrell_behavior (seat_no, event_at DESC);
CREATE INDEX idx_ife_cockrell_type_event
    ON ife_cockrell_behavior (behavior_type, event_at DESC);
