INSERT INTO data_type (
    code, name, message_type, udp_port,
    source_system_code, source_device_code, parser_code,
    enabled, supports_csv_import, supports_csv_export, supports_pdf_export,
    sort_order, description
) VALUES
('QAR', 'QAR 飞行数据', 'qar.frame', 8090,
 'SIMULATOR', 'SIM-QAR', 'qarParser',
 true, true, true, true, 10, '飞机位置、速度、高度、姿态和油量原始数据'),
('GROUND_TASK', '仿真任务数据', 'ground.task', 8091,
 'SIMULATOR', 'SIM-GROUND', 'groundTaskParser',
 true, true, true, true, 20, '地面仿真任务状态快照'),
('GROUND_TRAFFIC_RECORD', '流量窗口数据', 'ground.traffic_record', 8092,
 'SIMULATOR', 'SIM-GROUND', 'trafficRecordParser',
 true, true, true, true, 30, '乘客终端流量窗口批量报文'),
('GROUND_SESSION_SUMMARY', '会话摘要数据', 'ground.session_summary', 8093,
 'SIMULATOR', 'SIM-GROUND', 'sessionSummaryParser',
 true, true, true, true, 40, '乘客终端会话摘要批量报文'),
('SMART_WINDOW_STATUS', '智能舷窗状态', 'smart_window.status', 8094,
 'SIMULATOR', 'SIM-WINDOW', 'smartWindowParser',
 true, false, true, true, 50, '全机智能舷窗状态批量报文'),
('IFE_633_BEHAVIOR', '633 IFE 乘客行为', 'ife_633.behavior', 8095,
 'SIMULATOR', 'SIM-IFE-633', 'ife633Parser',
 true, false, true, true, 60, '633 IFE 电影、音乐、投屏和上网行为'),
('IFE_COCKRELL_BEHAVIOR', '科克瑞尔 IFE 乘客行为', 'ife_cockrell.behavior', 8096,
 'SIMULATOR', 'SIM-IFE-COCKRELL', 'ifeCockrellParser',
 true, false, true, true, 70, '科克瑞尔 IFE 电影、音乐、上网和购物行为')
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    message_type = EXCLUDED.message_type,
    udp_port = EXCLUDED.udp_port,
    source_system_code = EXCLUDED.source_system_code,
    source_device_code = EXCLUDED.source_device_code,
    parser_code = EXCLUDED.parser_code,
    enabled = EXCLUDED.enabled,
    supports_csv_import = EXCLUDED.supports_csv_import,
    supports_csv_export = EXCLUDED.supports_csv_export,
    supports_pdf_export = EXCLUDED.supports_pdf_export,
    sort_order = EXCLUDED.sort_order,
    description = EXCLUDED.description;
