CREATE TABLE tag (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name varchar(64) NOT NULL,
    color varchar(7) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    version integer NOT NULL DEFAULT 1,
    created_by uuid NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_tag_name CHECK (length(btrim(name)) BETWEEN 1 AND 64),
    CONSTRAINT ck_tag_color CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_tag_version CHECK (version > 0)
);

CREATE UNIQUE INDEX uk_tag_name_ci ON tag (lower(name));
CREATE INDEX idx_tag_enabled_name ON tag (enabled, name);

CREATE TABLE data_record_tag (
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    tag_id uuid NOT NULL REFERENCES tag(id) ON DELETE RESTRICT,
    created_by uuid NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (record_id, tag_id)
);

CREATE INDEX idx_data_record_tag_tag_record ON data_record_tag (tag_id, record_id);

CREATE TABLE data_annotation (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    record_id uuid NOT NULL REFERENCES data_record(id) ON DELETE CASCADE,
    content varchar(2000) NOT NULL,
    version integer NOT NULL DEFAULT 1,
    is_deleted boolean NOT NULL DEFAULT false,
    deleted_at timestamptz,
    deleted_by uuid REFERENCES app_user(id) ON DELETE RESTRICT,
    created_by uuid NOT NULL REFERENCES app_user(id) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_annotation_content CHECK (length(btrim(content)) BETWEEN 1 AND 2000),
    CONSTRAINT ck_annotation_version CHECK (version > 0),
    CONSTRAINT ck_annotation_deleted CHECK (
        (is_deleted = false AND deleted_at IS NULL AND deleted_by IS NULL) OR
        (is_deleted = true AND deleted_at IS NOT NULL)
    )
);

CREATE INDEX idx_annotation_record_created_active
    ON data_annotation (record_id, created_at) WHERE is_deleted = false;
CREATE INDEX idx_annotation_deleted_cleanup
    ON data_annotation (is_deleted, deleted_at);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action varchar(64) NOT NULL,
    target_type varchar(64) NOT NULL,
    target_id varchar(128),
    operator_id uuid REFERENCES app_user(id) ON DELETE RESTRICT,
    request_ip inet,
    before_value jsonb,
    after_value jsonb,
    result varchar(16) NOT NULL,
    trace_id varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_audit_result CHECK (result IN ('SUCCESS', 'FAILURE'))
);

CREATE INDEX idx_audit_target_created ON audit_log (target_type, target_id, created_at DESC);
CREATE INDEX idx_audit_operator_created ON audit_log (operator_id, created_at DESC);
CREATE INDEX idx_audit_action_created ON audit_log (action, created_at DESC);
CREATE INDEX idx_audit_created ON audit_log (created_at DESC);
